src/Lykke.Service.PayBackoffice/Areas/LykkePay/Models/InvoicesListViewModel.cs
using BackOffice.Models;
using Lykke.Service.PayInternal.Client.Models.Merchant;
using Lykke.Service.PayInternal.Client.Models.PaymentRequest;
using Lykke.Service.PayInvoice.Client.Models.Invoice;
using System.Collections.Generic;

namespace BackOffice.Areas.LykkePay.Models
{
    public class InvoicesListViewModel : PagedListModel
    {
        public IReadOnlyList<MerchantModel> Merchants { get; set; }
        public IReadOnlyList<InvoiceModel> Invoices { get; set; }
        public string SelectedMerchant { get; set; }
        public bool IsEditAccess { get; set; }
        public bool IsFullAccess { get; set; }
    }
}

src/Lykke.Service.PayBackoffice/Areas/LykkePay/Controllers/InvoicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using BackOffice.Filters;
using Core.Users;
using BackOffice.Controllers;
using BackOffice.Areas.LykkePay.Models;
using Lykke.Service.PayInternal.Client;
using Lykke.Service.PayInvoice.Client;
using Lykke.Service.PayInternal.Client.Models.Merchant;
using PagedList.Core;
using Lykke.Service.PayInvoice.Client.Models.Invoice;
using Lykke.Service.PayInternal.Client.Models.PaymentRequest;

namespace Lykke.Service.PayBackoffice.Areas.LykkePay.Controllers
{
    [Authorize]
    [Area("LykkePay")]
    [FilterFeaturesAccess(UserFeatureAccess.LykkePayMerchantsView)]
    public class InvoicesController : Controller
    {
        private readonly IPayInternalClient _payInternalClient;
        private readonly IPayInvoiceClient _payInvoiceClient;
        private const string ErrorMessageAnchor = "#errorMessage";

        public InvoicesController(
            IPayInternalClient payInternalClient,
            IPayInvoiceClient payInvoiceClient)
        {
            _payInternalClient = payInternalClient;
            _payInvoiceClient = payInvoiceClient;
        }
        public IActionResult Index(string merchantId)
        {
            var model = new InvoicesListViewModel();
            model.SelectedMerchant = merchantId;
            return View(model);
        }
        [HttpPost]
        public async Task<ActionResult> InvoicesPage(InvoicesListViewModel vm)
        {
            vm.Merchants = await _payInternalClient.GetMerchantsAsync();
            vm.CurrentPage = 1;
            vm.IsFullAccess = (await this.GetUserRolesPair()).HasAccessToFeature(UserFeatureAccess.LykkePayMerchantsFull);
            return View(vm);
        }
        [HttpPost]
        public async Task<ActionResult> InvoicesList(InvoicesListViewModel vm)
        {
            var invoices = await _payInvoiceClient.GetMerchantInvoicesAsync(vm.SelectedMerchant);
            vm.PageSize = vm.PageSize == 0 ? 10 : vm.PageSize;
            var pagesize = Request.Cookies["PageSize"];
            if (pagesize != null)
                vm.PageSize = Convert.ToInt32(pagesize);
            
            
            var pagedlist = new List<InvoiceModel>();
            var pageCount = Convert.ToInt32(Math.Ceiling((double)invoices.Count() / vm.PageSize));
            var currentPage = vm.CurrentPage == 0 ? 1 : vm.CurrentPage;
            if (invoices.Count() != 0)
                pagedlist = invoices.AsQueryable().ToPagedList(currentPage, vm.PageSize).ToList();
            var viewmodel = new InvoicesListViewModel()
            {
                Invoices = pagedlist,
                PageSize = vm.PageSize,
                Count = pageCount,
                CurrentPage = currentPage,
                IsEditAccess = (await this.GetUserRolesPair()).HasAccessToFeature(UserFeatureAccess.LykkePayMerchantsEdit),
                IsFullAccess = (await this.GetUserRolesPair()).HasAccessToFeature(UserFeatureAccess.LykkePayMerchantsFull)
            };
            return View(viewmodel);
        }
        public IActionResult PaymentRequests(string invoiceId)
        {
            var model = new InvoicePaymentRequestsViewModel();
            model.InvoiceId = invoiceId;
            return View(model);
        }
        [HttpPost]
        public async Task<ActionResult> PaymentRequestsPage(InvoicePaymentRequestsViewModel vm)
        {
            var invoice = await _payInvoiceClient.GetInvoiceAsync(vm.InvoiceId);
            vm.CurrentPage = 1;
            vm.MerchantId = invoice.MerchantId;
            vm.PaymentRequestId = invoice.PaymentRequestId;
            return View(vm);
        }
        [HttpPost]
        public async Task<ActionResult> PaymentRequestsList(InvoicePaymentRequestsViewModel vm)
        {
            var request = await _payInternalClient.GetPaymentRequestAsync(vm.MerchantId, vm.PaymentRequestId);
            var list = new List<PaymentRequestModel>();
            list.Add(request);
            vm.PageSize = vm.PageSize == 0 ? 10 : vm.PageSize;
            var pagesize = Request.Cookies["PageSize"];
            if (pagesize != null)
                vm.PageSize = Convert.ToInt32(pagesize);


            var pagedlist = new List<PaymentRequestModel>();
            var pageCount = Convert.ToInt32(Math.Ceiling((double)list.Count() / vm.PageSize));
            var currentPage = vm.CurrentPage == 0 ? 1 : vm.CurrentPage;
            if (list.Count() != 0)
                pagedlist = list.AsQueryable().ToPagedList(currentPage, vm.PageSize).ToList();
            var viewmodel = new InvoicePaymentRequestsViewModel()
            {
                Requests = pagedlist,
                PageSize = vm.PageSize,
                Count = pageCount,
                CurrentPage = currentPage
            };
            return View(viewmodel);
        }
    }
}

src/Lykke.Service.PayBackoffice/Areas/LykkePay/Controllers/PaymentRequestsController.cs
using BackOffice.Areas.LykkePay.Models;
using BackOffice.Binders;
using BackOffice.Controllers;
using BackOffice.Helpers;
using BackOffice.Translates;
using Lykke.Service.BackofficeMembership.Client.Filters;
using Lykke.Service.PayInternal.Client;
using Lykke.Service.PayMerchant.Client.Models;
using Lykke.Service.PayInternal.Client.Models.PaymentRequest;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PagedList.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Lykke.Service.PayMerchant.Client;

namespace BackOffice.Areas.LykkePay.Controllers
{
    [Authorize]
    [Area("LykkePay")]
    [FilterFeaturesAccess(UserFeatureAccess.LykkePayPaymentRequests)]
    public class PaymentRequestsController : Controller
    {
        protected string BlockchainExplorerUrl
               => AzureBinder.BlockchainExplorerUrl;

        protected string EthereumBlockchainExplorerUrl
            => AzureBinder.EthereumBlockchainExplorerUrl;

        private readonly IPayInternalClient _payInternalClient;
        private readonly IPayMerchantClient _payMerchantClient;
        private readonly IMapper _mapper;

        public PaymentRequestsController(
            IPayInternalClient payInternalClient,
            IMapper mapper, 
            IPayMerchantClient payMerchantClient)
        {
            _payInternalClient = payInternalClient;
            _mapper = mapper;
            _payMerchantClient = payMerchantClient;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> PaymentRequestsPage(string merchant = "")
        {
            var merchants = await _payMerchantClient.Api.GetAllAsync();

            if (!string.IsNullOrEmpty(merchant) && !merchants.Select(x => x.Id).Contains(merchant))
            {
                return this.JsonFailResult(Phrases.InvalidValue, "#merchant");
            }

            if (merchants.Any())
            {
                if (string.IsNullOrEmpty(merchant))
                {
                    merchant = merchants.Select(x => x.Id).First();
                }
            }
            return View(new PaymentRequestPageViewModel()
            {
                SelectedMerchant = merchant,
                Merchants = merchants,
                Statuses = Enum.GetValues(typeof(PaymentRequestStatus)).Cast<PaymentRequestStatus>().ToList()
        });
        }

        [HttpPost]
        public async Task<ActionResult> PaymentRequestsList(PaymentRequestPageViewModel vm)
        {
            if (string.IsNullOrEmpty(vm.SelectedMerchant))
                return this.JsonFailResult(Phrases.FieldShouldNotBeEmpty, "#selectedMerchant");

            var merchant = new MerchantModel();
            if (!string.IsNullOrEmpty(vm.MerchantName))
            {
                var merchants = await _payMerchantClient.Api.GetAllAsync();
                merchant = merchants.FirstOrDefault(m => String.Equals(m.Name, vm.MerchantName, StringComparison.CurrentCultureIgnoreCase));
            }

            IReadOnlyList<PaymentRequestModel> requests;
            if (!string.IsNullOrEmpty(merchant?.Id))
                requests = await _payInternalClient.GetPaymentRequestsAsync(merchant.Id);
            else
                requests = await _payInternalClient.GetPaymentRequestsAsync(vm.SelectedMerchant);

            vm.PageSize = vm.PageSize == 0 ? 10 : vm.PageSize;
            var pagesize = Request.Cookies["PageSize"];
            if (pagesize != null)
                vm.PageSize = Convert.ToInt32(pagesize);

            var list = new List<PaymentRequestModel>(requests).AsQueryable();
            try
            {
                if (!string.IsNullOrEmpty(vm.SearchValue))
                {
                    list = list.Where(x =>
                        (!string.IsNullOrEmpty(x.WalletAddress) && x.WalletAddress.Contains(vm.SearchValue))
                        || x.Id.Contains(vm.SearchValue)
                        || (!string.IsNullOrEmpty(x.OrderId) && x.OrderId.Contains(vm.SearchValue))).AsQueryable();
                }

                if (vm.SelectedStatus != PaymentRequestStatus.None)
                    list = list.Where(x => x.Status.ToString() == vm.SelectedStatus.ToString()).AsQueryable();
            }
            catch (Exception ex)
            {
                list = new List<PaymentRequestModel>().AsQueryable();
            }

            var pagedlist = new List<PaymentRequestModel>();
            var pageCount = Convert.ToInt32(Math.Ceiling((double)list.Count() / vm.PageSize));
            var currentPage = vm.CurrentPage == 0 ? 1 : vm.CurrentPage;
            if (list.Count() != 0)
                pagedlist = list.OrderByDescending(x=>x.DueDate).ToPagedList(currentPage, vm.PageSize).ToList();

            var requestViewModels = _mapper.Map<PaymentRequestViewModel[]>(pagedlist);
            if (requestViewModels.Any())
            {
                var assetsList = (await _payInternalClient.GetAssetGeneralSettingsAsync()).ToArray();
                foreach (var requestViewModel in requestViewModels)
                {
                    requestViewModel.PaymentAssetGeneralSettings = assetsList.FirstOrDefault(a =>
                        string.Equals(a.AssetDisplayId, requestViewModel.PaymentAssetId,
                            StringComparison.OrdinalIgnoreCase));

                    requestViewModel.SettlementAssetGeneralSettings = assetsList.FirstOrDefault(a =>
                        string.Equals(a.AssetDisplayId, requestViewModel.SettlementAssetId,
                            StringComparison.OrdinalIgnoreCase));
                }
            }

            var viewModel = new PaymentRequestListViewModel()
            {
                Requests = requestViewModels,
                SelectedMerchant = vm.SelectedMerchant,
                BlockchainExplorerUrl = BlockchainExplorerUrl + "address/",
                EthereumBlockchainExplorerUrl = EthereumBlockchainExplorerUrl.TrimEnd('/') + "/address/",
                PageSize = vm.PageSize,
                Count = pageCount,
                CurrentPage = currentPage
            };

            return View(viewModel);
        }
    }
}

src/Lykke.Service.PayBackoffice/Areas/LykkePay/Views/Invoices/Index.cshtml
@model BackOffice.Areas.LykkePay.Models.InvoicesListViewModel

<ul id="tabs" class="nav nav-tabs">
    <li id="invoices"><a data-toggle="tab" onclick="selectTab(this.parentNode.id, '@Url.Action("InvoicesPage")')">Invoices</a></li>
</ul>

<div id="InvoicesPage" style="margin: 10px"></div>

<script>
    function selectTab(tabId, url) {
        if ($('#' + tabId).hasClass('active'))
            return;
        $('#tabs').children('li').each(function() {
            (this.id === tabId) && $('#' + this.id).addClass('active') || $('#' + this.id).removeClass('active');
        });
        requests.doRequest({ url: url, divResult: '#InvoicesPage', params: { selectedMerchant: '@Model.SelectedMerchant'}, });
    }
    selectTab('invoices', '@Url.Action("InvoicesPage")');
</script>

src/Lykke.Service.PayBackoffice/Areas/LykkePay/Views/Invoices/InvoicesList.cshtml
@using BackOffice.Translates
@model BackOffice.Areas.LykkePay.Models.InvoicesListViewModel
@if (Model.Invoices != null && Model.Invoices.Any())
{
    @Html.RenderPagination(Model.PageSize, Model.Count, Model.CurrentPage, "InvoicesList", "frmInvoicesPage", "invoicesList")
    <table class="table table-striped">
        <tr>
            <th>
                Number
            </th>
            <th>
                Amount
            </th>
            <th>
                ClientEmail
            </th>
            <th>
                ClientName
            </th>
            <th>
                CreatedDate
            </th>
            <th>
                DueDate
            </th>
            <th>
                Note
            </th>
            <th>
                PaymentAssetId
            </th>
            <th>
                PaymentRequestId
            </th>
            <th>
                SettlementAssetId
            </th>
            <th>
                Status
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.Invoices)
                {
            <tr>
                <td>
                    @item.Number
                </td>
                <td>
                    @item.Amount
                </td>
                <td>
                    @item.ClientEmail
                </td>
                <td>
                    @item.ClientName
                </td>
                <td>
                    @item.CreatedDate
                </td>
                <td>
                    @item.DueDate
                </td>
                <td>
                    @item.Note
                </td>
                <td>
                    @item.PaymentAssetId
                </td>
                <td>
                    @item.PaymentRequestId
                </td>
                <td>
                    @item.SettlementAssetId
                </td>
                <td>
                    @item.Status
                </td>
                <td>
                    <a href="javascript:void(0);" class="requests" invoiceId="@item.Id">requests</a>
                </td>
                <td style="text-align: right"></td>
            </tr>
        }
    </table>
}
else
{
    <div class="row">
        <p>@Phrases.NoRecordsFound</p>
    </div>
}
<script>
    $(".requests").click(function (e) {
        var invoiceId = e.currentTarget.getAttribute("invoiceId");
            var options = {
                url: '@Url.Action("PaymentRequests", "Invoices", new { area = "LykkePay" })', type: 'POST', headers: { 'RequestVerificationToken': getAntiForgeryCookie() }, data: {
                    'invoiceId': invoiceId
                } };
            $.ajax(options)
                .then(function(result) {

                    var historyItem = {
                        url: '@Url.Action("PaymentRequests", "Invoices", new { area = "LykkePay" })',
                        div: '#pamain',
                        type: 'menu'
                    };

                    historyManager.put(historyItem);

                    $('#pamain').html(result);
                    layout.ressize();
                }).fail(function(fr) {
                    if (xhr && (xhr.status === 403 || xhr.status === 401)) {
                        console.log("Forbidden redirecting to index...");
                        window.location = '@Url.Action("Index", "Home")';
                    } else {
                        activeItem.addClass('smiSel');
                        $('#pamain').html(fr.responseText);
                    }
                });
        });
</script>

src/Lykke.Service.PayBackoffice/Areas/LykkePay/Views/Invoices/InvoicesPage.cshtml
@model BackOffice.Areas.LykkePay.Models.InvoicesListViewModel
@using BackOffice.Models
@{
    IEnumerable<ItemViewModel> merchantList = Model.Merchants.
        Select(m => new ItemViewModel { Id = m.Id, Title = m.Name }).ToArray();
    if (!string.IsNullOrEmpty(Model.SelectedMerchant))
    {
        merchantList.FirstOrDefault(x => x.Id == Model.SelectedMerchant).Selected = true;
    }
}
<div>
    <h1>Invoices</h1>
    <hr />
    <form id="frmInvoicesPage">
        @Html.HiddenFor(x => x.CurrentPage)
        @Html.HiddenFor(x => x.PageSize)
        <div class="row">
            <div class="col-md-2 col-md-offset-0 input-lg">
                @Html.RenderSelect2("", "SelectedMerchant", merchantList, false, "Select merchant...")
            </div>
        </div>
    </form>
    <div id="invoicesList"></div>
</div>

<script>
    $(function () {
            var $merchantSelect = $('#selectedMerchant');
            $merchantSelect.select2().on("change",
                function (e) {
                    requests.doRequest({
                        url: '@Url.Action("InvoicesList")',
                        formId: '#frmInvoicesPage',
                        divResult: '#invoicesList'
                    });
                });
            $('.select2-container--default').width(200);
            requests.doRequest({ url: '@Url.Action("InvoicesList")', formId: '#frmInvoicesPage', divResult: '#invoicesList' });
        });
</script>

src/Lykke.Service.PayBackoffice/Areas/LykkePay/Views/Invoices/PaymentRequests.cshtml
@model BackOffice.Areas.LykkePay.Models.InvoicePaymentRequestsViewModel

<ul id="tabs" class="nav nav-tabs">
    <li id="invoices"><a data-toggle="tab" onclick="selectTab(this.parentNode.id, '@Url.Action("InvoicesPage")')">Invoices</a></li>
</ul>

<div id="InvoicePaymentRequestsPage" style="margin: 10px"></div>

<script>
    requests.doRequest({ url: '@Url.Action("PaymentRequestsPage")', params: { invoiceId: '@Model.InvoiceId'}, divResult: '#InvoicePaymentRequestsPage' });
</script>

src/Lykke.Service.PayBackoffice/Areas/LykkePay/Views/Invoices/PaymentRequestsList.cshtml
@using BackOffice.Translates
@model BackOffice.Areas.LykkePay.Models.InvoicePaymentRequestsViewModel

@if (Model.Requests != null && Model.Requests.Any())
{
    @Html.RenderPagination(Model.PageSize, Model.Count, Model.CurrentPage, "PaymentRequestsList", "frmInvoicePaymentRequestsPage", "invoicePaymentRequestsList")
    <table class="table table-striped">
        <tr>
            <th>
                Id
            </th>
            <th>
                Amount
            </th>
            <th>
                DueDate
            </th>
            <th>
                MarkupFixedFee
            </th>
            <th>
                MarkupPercent
            </th>
            <th>
                MarkupPips
            </th>
            <th>
                ExternalOrderId
            </th>
            <th>
                PaidAmount
            </th>
            <th>
                PaidDate
            </th>
            <th>
                CreatedOn
            </th>
            <th>
                PaymentAssetId
            </th>
            <th>
                SettlementAssetId
            </th>
            <th>
                Status
            </th>
            <th>
                Error
            </th>
            <th>
                WalletAddress
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.Requests)
        {
            <tr>
                <td>
                    @item.Id
                </td>
                <td>
                    @item.Amount
                </td>
                <td>
                    @item.DueDate
                </td>
                <td>
                    @item.MarkupFixedFee
                </td>
                <td>
                    @item.MarkupPercent
                </td>
                <td>
                    @item.MarkupPips
                </td>
                <td>
                    @item.ExternalOrderId
                </td>
                <td>
                    @item.PaidAmount
                </td>
                <td>
                    @item.PaidDate
                </td>
                <td>
                    @item.Timestamp
                </td>
                <td>
                    @item.PaymentAssetId
                </td>
                <td>
                    @item.SettlementAssetId
                </td>
                <td>
                    @item.Status
                </td>
                <td>
                    @item.ProcessingError
                </td>
                <td style="text-align: right">
                    @*<button class="btn btn-xs btn-default btn-raised"
                                onclick="ui.showDialog('@Url.Action("AddOrEditStaffDialog")', { Id: '@item.Id', merchant: '@item.MerchantId' });">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                        </button>
                        <button class="btn btn-xs btn-danger btn-raised"
                                onclick="ui.showDialog('@Url.Action("DeleteStaffDialog")', { Id: '@item.Id', merchant: '@item.MerchantId' });">
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                        </button>*@
                </td>
            </tr>
        }
    </table>
}
else
{
    <p>@Phrases.NoRecordsFound</p>
}

src/Lykke.Service.PayBackoffice/Areas/LykkePay/Views/Invoices/PaymentRequestsPage.cshtml
@model BackOffice.Areas.LykkePay.Models.InvoicePaymentRequestsViewModel

<div>
    <a href="javascript: void(0);" class="backbtn">Back</a>
    <h1>Payment requests for Invoice: @Model.InvoiceId</h1>
    <hr />
    <form id="frmInvoicePaymentRequestsPage">
        @Html.HiddenFor(x => x.CurrentPage)
        @Html.HiddenFor(x => x.PageSize)
        @Html.HiddenFor(x => x.InvoiceId)
        @Html.HiddenFor(x => x.MerchantId)
        @Html.HiddenFor(x => x.PaymentRequestId)
    </form>
    <div id="invoicePaymentRequestsList"></div>
</div>

<script>
    requests.doRequest({ url: '@Url.Action("PaymentRequestsList")', formId: '#frmInvoicePaymentRequestsPage', divResult: '#invoicePaymentRequestsList' });

    $(".backbtn").click(function (e) {

            var options = {
            url: '@Url.Action("Index", "Invoices", new { area = "LykkePay" })', type: 'POST', headers: { 'RequestVerificationToken': getAntiForgeryCookie() }, data: { 'merchantId': '@Model.MerchantId' }
        };
            debugger;
            $.ajax(options)
                .then(function(result) {

                    var historyItem = {
                        url: '@Url.Action("Index", "Invoices", new { area = "LykkePay" })',
                        div: '#pamain',
                        type: 'menu'
                    };

                    historyManager.put(historyItem);

                    $('#pamain').html(result);
                    layout.ressize();
                }).fail(function(fr) {
                    if (xhr && (xhr.status === 403 || xhr.status === 401)) {
                        console.log("Forbidden redirecting to index...");
                        window.location = '@Url.Action("Index", "Home")';
                    } else {
                        activeItem.addClass('smiSel');
                        $('#pamain').html(fr.responseText);
                    }
                });
        });
</script>