src/Lykke.Service.PayBackoffice/Areas/LykkePay/Models/Merchants/AddMerchantVolatilitySettingsViewModel.cs
namespace BackOffice.Areas.LykkePay.Models.Merchants
{
    public class AddMerchantVolatilitySettingsViewModel
    {
        public string Caption { get; set; }
        public string Width { get; set; }
        public string ZeroCoverageAssetPairs { get; set; }
        public string MerchantId { get; set; }
    }
}

src/Lykke.Service.PayBackoffice/Areas/LykkePay/Models/Merchants/AddOrEditMerchantDialogViewModel.cs
using BackOffice.Models;

namespace BackOffice.Areas.LykkePay.Models
{
    public class AddOrEditMerchantDialogViewModel : IPersonalAreaDialog
    {
        public bool IsNewMerchant { get; set; }
        public string Caption { get; set; }
        public string Width { get; set; }
        public string Id { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string ApiKey { get; set; }
        public string LwId { get; set; }
        public string LogoImage { get; set; }
        public string Email { get; set; }
    }
    public class DeleteMerchantDialogViewModel : IPersonalAreaDialog
    {
        public string Caption { get; set; }
        public string Width { get; set; }

        public string Name { get; set; }
        public string Id { get; set; }
    }
}

src/Lykke.Service.PayBackoffice/Areas/LykkePay/Models/Merchants/AddOrEditMerchantSettingDialog.cs
using BackOffice.Models;
using Lykke.Service.PayInvoice.Core.Domain;

namespace BackOffice.Areas.LykkePay.Models.Merchants
{
    public class AddOrEditMerchantSettingDialog : IPersonalAreaDialog
    {
        public string Caption { get; set; }
        public string Width { get; set; }
        public string MerchantId { get; set; }
        public string BaseAsset { get; set; }
    }
}

src/Lykke.Service.PayBackoffice/Areas/LykkePay/Models/Merchants/AddOrEditMerchantTransferSettingsDialog.cs
using System.Collections.Generic;
using BackOffice.Models;
using Lykke.Service.PayTransferValidation.Client.Models.Rule;

namespace BackOffice.Areas.LykkePay.Models.Merchants
{
    public class AddOrEditMerchantTransferSettingsDialog : IPersonalAreaDialog
    {
        public string Caption { get; set; }
        public string Width { get; set; }
        public string MerchantId { get; set; }
        public string RuleId { get; set; }
        public string RuleInput { get; set; }
        public bool Enabled { get; set; }
        public bool IsNew { get; set; }
        public IEnumerable<RegisteredRuleModel> RuleList { get; set; }
    }
}

src/Lykke.Service.PayBackoffice/Areas/LykkePay/Models/Merchants/AddOrEditMerchantVolatilitySettingsDialog.cs
using BackOffice.Models;

namespace BackOffice.Areas.LykkePay.Models.Merchants
{
    public class AddOrEditMerchantVolatilitySettingsDialog : IPersonalAreaDialog
    {
        public string Caption { get; set; }
        public string Width { get; set; }
        public string MerchantId { get; set; }
        public string ZeroCoverageAssetPairs { get; set; }
        public bool IsDeltaSpreadFixed { get; set; }
        public bool IsNew { get; set; }
    }
}

src/Lykke.Service.PayBackoffice/Areas/LykkePay/Models/Merchants/DeleteMerchantTransferSettingsDialogViewModel.cs
using BackOffice.Models;

namespace BackOffice.Areas.LykkePay.Models.Merchants
{
    public class DeleteMerchantTransferSettingsDialogViewModel : IPersonalAreaDialog
    {
        public string Caption { get; set; }
        public string Width { get; set; }
        public string MerchantId { get; set; }
        public string RuleId { get; set; }
        public string RuleDisplayName { get; set; }
    }
}

src/Lykke.Service.PayBackoffice/Areas/LykkePay/Models/Merchants/DeleteMerchantVolatilitySettingsDialogViewModel.cs
using BackOffice.Models;

namespace BackOffice.Areas.LykkePay.Models.Merchants
{
    public class DeleteMerchantVolatilitySettingsDialogViewModel : IPersonalAreaDialog
    {
        public string Caption { get; set; }
        public string Width { get; set; }
        public string MerchantId { get; set; }
    }
}

src/Lykke.Service.PayBackoffice/Areas/LykkePay/Models/Merchants/MerchantCertificateViewModel.cs
using BackOffice.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BackOffice.Areas.LykkePay.Models.Merchants
{
    public class MerchantCertificateViewModel : IPersonalAreaDialog
    {
        public string Caption { get; set; }
        public string Width { get; set; }
        public string MerchantId { get; set; }
        public string MerchantDisplayName { get; set; }
    }

    public class MerchantRsaKeys
    {
        public string Private { get; set; }
        public string Public { get; set; }
    }
}

src/Lykke.Service.PayBackoffice/Areas/LykkePay/Models/Merchants/MerchantSettingsViewModel.cs
using BackOffice.Models;
using Lykke.Service.PayMerchant.Client.Models;
using Lykke.Service.PayInvoice.Core.Domain;
using System.Collections.Generic;

namespace BackOffice.Areas.LykkePay.Models
{
    public class MerchantSettingsListViewModel : PagedListModel
    {
        public IEnumerable<MerchantModel> Merchants { get; set; }
        public bool IsEditAccess { get; set; }
        public bool IsFullAccess { get; set; }
        public string SelectedMerchant { get; set; }
        public IEnumerable<MerchantSetting> Settings { get; set; }
    }
}

src/Lykke.Service.PayBackoffice/Areas/LykkePay/Models/Merchants/MerchantTransferSettingsListViewModel.cs
using System.Collections.Generic;
using BackOffice.Models;
using Lykke.Service.PayMerchant.Client.Models;
using Lykke.Service.PayTransferValidation.Client.Models.MerchantConfiguration;

namespace BackOffice.Areas.LykkePay.Models.Merchants
{
    public class MerchantTransferSettingsListViewModel : PagedListModel
    {
        public IEnumerable<MerchantModel> Merchants { get; set; }
        public bool IsEditAccess { get; set; }
        public bool IsFullAccess { get; set; }
        public string SelectedMerchant { get; set; }
        public IEnumerable<LineModel> Settings { get; set; }
    }
}

src/Lykke.Service.PayBackoffice/Areas/LykkePay/Models/Merchants/MerchantVolatilitySettingsListViewModel.cs
using System.Collections.Generic;
using BackOffice.Models;
using Lykke.Service.PayMerchant.Client.Models;

namespace BackOffice.Areas.LykkePay.Models.Merchants
{
    public class MerchantVolatilitySettingsListViewModel : PagedListModel
    {
        public IEnumerable<MerchantModel> Merchants { get; set; }
        public bool IsEditAccess { get; set; }
        public bool IsFullAccess { get; set; }
        public string SelectedMerchant { get; set; }
        public IEnumerable<VolatilitySettingsResponse> Settings { get; set; }
    }
}

src/Lykke.Service.PayBackoffice/Areas/LykkePay/Models/Merchants/MerchantsListViewModel.cs
using BackOffice.Models;
using Lykke.Service.PayMerchant.Client.Models;
using System.Collections.Generic;

namespace BackOffice.Areas.LykkePay.Models
{
    public class MerchantsListViewModel : PagedListModel
    {
        public IEnumerable<MerchantModel> Merchants { get; set; }
        public bool IsEditAccess { get; set; }
        public bool IsFullAccess { get; set; }
        public string SearchValue { get; set; }
        public bool FilterByEmail { get; set; }
    }
}

src/Lykke.Service.PayBackoffice/Areas/LykkePay/Models/Merchants/UploadLogoDialogViewModel.cs
using BackOffice.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BackOffice.Areas.LykkePay.Models.Merchants
{
    public class UploadLogoDialogViewModel : IPersonalAreaDialog
    {
        public string MerchantId { get; set; }
        public string LogoImage { get; set; }
        public string Caption { get; set; }
        public string Width { get; set; }
    }
}

src/Lykke.Service.PayBackoffice/Areas/LykkePay/Controllers/MerchantsController.cs
using BackOffice.Areas.LykkePay.Models;
using BackOffice.Areas.LykkePay.Models.Merchants;
using BackOffice.Controllers;
using BackOffice.Helpers;
using BackOffice.Translates;
using Lykke.Service.BackofficeMembership.Client;
using Lykke.Service.BackofficeMembership.Client.Filters;
using Lykke.Service.PayAuth.Client;
using Lykke.Service.PayInternal.Client;
using Lykke.Service.PayInvoice.Client;
using Lykke.Service.PayInvoice.Core.Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PagedList.Core;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Lykke.Service.PayMerchant.Client;
using Lykke.Service.PayMerchant.Client.Models;
using Common;
using System.IO.Compression;
using Lykke.Common.Log;
using Lykke.Service.PayAuth.Client.Models.GenerateRsaKeys;
using Common.Log;
using Lykke.Common.ApiLibrary.Exceptions;
using Lykke.Service.PayTransferValidation.Client;
using Lykke.Service.PayTransferValidation.Client.Models.MerchantConfiguration;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace BackOffice.Areas.LykkePay.Controllers
{
    [Authorize]
    [Area("LykkePay")]
    [FilterFeaturesAccess(UserFeatureAccess.LykkePayMerchantsView)]
    public class MerchantsController : Controller
    {
        private readonly IPayInternalClient _payInternalClient;
        private readonly IPayAuthClient _payAuthClient;
        private readonly IPayInvoiceClient _payInvoiceClient;
        private readonly IPayMerchantClient _payMerchantClient;
        private readonly IPayTransferValidationClient _payTransferValidationClient;
        private readonly ILog _log;
        private const string ErrorMessageAnchor = "#errorMessage";

        public MerchantsController(
            IPayInternalClient payInternalClient,
            IPayAuthClient payAuthClient,
            IPayInvoiceClient payInvoiceClient,
            IPayMerchantClient payMerchantClient,
            ILogFactory logFactory, 
            IPayTransferValidationClient payTransferValidationClient)
        {
            _payInternalClient = payInternalClient;
            _payAuthClient = payAuthClient;
            _payInvoiceClient = payInvoiceClient;
            _payMerchantClient = payMerchantClient;
            _payTransferValidationClient = payTransferValidationClient;
            _log = logFactory.CreateLog(this);
        }

        #region Merchants

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult MerchantsPage()
        {
            var model = new MerchantsListViewModel
            {
                CurrentPage = 1,
                IsFullAccess = this.GetUserRolesPair().HasAccessToFeature(UserFeatureAccess.LykkePayMerchantsFull)
            };

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> MerchantsList(MerchantsListViewModel vm)
        {
            var merchants = await _payMerchantClient.Api.GetAllAsync();
            vm.PageSize = vm.PageSize == 0 ? 10 : vm.PageSize;
            var pagesize = Request.Cookies["PageSize"];
            if (pagesize != null)
                vm.PageSize = Convert.ToInt32(pagesize);
            var list = new List<MerchantModel>(merchants).AsQueryable();
            if (!string.IsNullOrEmpty(vm.SearchValue) && !vm.FilterByEmail)
                list = list.Where(x =>
                    x.Name.ToLower().Contains(vm.SearchValue.ToLower()) ||
                    x.ApiKey.ToLower().Contains(vm.SearchValue.ToLower())).AsQueryable();
            if (vm.FilterByEmail)
            {
                try
                {
                    var allstaffs = await _payInvoiceClient.GetEmployeesAsync();
                    var filteredstaffs = allstaffs
                        .Where(s => !string.IsNullOrEmpty(s.Email) && s.Email.Contains(vm.SearchValue))
                        .GroupBy(x => x.MerchantId).ToList();
                    var filtered = new List<MerchantModel>();
                    foreach (var merchant in filteredstaffs)
                    {
                        var model = merchants.FirstOrDefault(m => m.Id == merchant.Key);
                        if (model != null)
                            filtered.Add(model);
                    }

                    list = filtered.AsQueryable();
                }
                catch (Exception)
                {
                    list = new List<MerchantModel>().AsQueryable();
                }
            }

            var pagedlist = new List<MerchantModel>();
            var pageCount = Convert.ToInt32(Math.Ceiling((double) list.Count() / vm.PageSize));
            var currentPage = vm.CurrentPage == 0 ? 1 : vm.CurrentPage;
            if (list.Count() != 0)
                pagedlist = list.ToPagedList(currentPage, vm.PageSize).ToList();
            var viewmodel = new MerchantsListViewModel()
            {
                Merchants = pagedlist,
                PageSize = vm.PageSize,
                Count = pageCount,
                CurrentPage = currentPage,
                IsEditAccess = (this.GetUserRolesPair()).HasAccessToFeature(UserFeatureAccess.LykkePayMerchantsEdit),
                IsFullAccess = (this.GetUserRolesPair()).HasAccessToFeature(UserFeatureAccess.LykkePayMerchantsFull)
            };
            return View(viewmodel);
        }

        [HttpPost]
        public async Task<ActionResult> AddOrEditMerchantDialog(string id = null)
        {
            var merchant = new MerchantModel();

            bool isNewMerchant = id == null;

            if (!isNewMerchant)
            {
                merchant = await _payMerchantClient.Api.GetByIdAsync(id);
            }

            var viewModel = new AddOrEditMerchantDialogViewModel
            {
                Caption = isNewMerchant ? "Add merchant" : "Edit merchant",
                IsNewMerchant = id == null,
                ApiKey = merchant.ApiKey,
                Id = id,
                LwId = merchant.LwId,
                Name = merchant.Name,
                DisplayName = merchant.DisplayName,
                Email = merchant.Email
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<ActionResult> AddOrEditMerchant(AddOrEditMerchantDialogViewModel vm)
        {
            var merchants = await _payMerchantClient.Api.GetAllAsync();

            if (string.IsNullOrEmpty(vm.Name))
                return this.JsonFailResult("MerchantId required", ErrorMessageAnchor);

            if (string.IsNullOrEmpty(vm.DisplayName))
                return this.JsonFailResult("DisplayName required", ErrorMessageAnchor);

            if (string.IsNullOrEmpty(vm.ApiKey))
                vm.ApiKey = StringUtils.GenerateId().Replace("-", string.Empty);

            if (string.IsNullOrEmpty(vm.Email) && vm.IsNewMerchant)
                return this.JsonFailResult("Email required", ErrorMessageAnchor);

            if (vm.IsNewMerchant)
            {
                if (merchants != null && merchants.Select(x => x.Name).Contains(vm.Name))
                {
                    return this.JsonFailResult(Phrases.AlreadyExists, "#name");
                }

                try
                {
                    var merchant = await _payMerchantClient.Api.CreateAsync(new CreateMerchantRequest
                    {
                        Name = vm.Name,
                        ApiKey = vm.ApiKey,
                        LwId = vm.LwId,
                        DisplayName = vm.DisplayName,
                        Email = vm.Email
                    });

                    await _payAuthClient.RegisterAsync(new Lykke.Service.PayAuth.Client.Models.RegisterRequest
                    {
                        ApiKey = vm.ApiKey,
                        ClientId = merchant.Id
                    });
                }
                catch (Exception ex)
                {
                    return this.JsonFailResult(ex.Message, ErrorMessageAnchor);
                }
            }
            else
            {
                MerchantModel existingMerchant = await _payMerchantClient.Api.GetByIdAsync(vm.Id);

                try
                {
                    var updateRequest = new UpdateMerchantRequest
                    {
                        Id = vm.Id,
                        ApiKey = vm.ApiKey,
                        LwId = vm.LwId,
                        Name = vm.Name,
                        DisplayName = vm.DisplayName,
                    };

                    if (string.IsNullOrEmpty(existingMerchant.Email))
                    {
                        if (!string.IsNullOrEmpty(vm.Email))
                            updateRequest.Email = vm.Email;
                    }

                    await _payMerchantClient.Api.UpdateAsync(updateRequest);

                    await _payAuthClient.UpdateApiKeyAsync(new Lykke.Service.PayAuth.Client.Models.UpdateApiKeyRequest
                    {
                        ApiKey = vm.ApiKey,
                        ClientId = vm.Id
                    });
                }
                catch (Exception ex)
                {
                    return this.JsonFailResult(ex.Message, ErrorMessageAnchor);
                }
            }

            return this.JsonRequestResult("#merchantsList", Url.Action("MerchantsList"));
        }

        [HttpPost]
        public async Task<ActionResult> UploadLogoDialog(string id = null)
        {
            var merchantfiles = (await _payInternalClient.GetFilesAsync(id)).ToList();
            byte[] merchantlogo = null;
            if (merchantfiles.Any())
                merchantlogo = await _payInternalClient.GetFileAsync(id, merchantfiles[0].Id);

            var viewModel = new UploadLogoDialogViewModel
            {

src/Lykke.Service.PayBackoffice/Areas/LykkePay/Views/Merchants/AddOrEditMerchantSettingDialog.cshtml
@using BackOffice.Translates
@model BackOffice.Areas.LykkePay.Models.Merchants.AddOrEditMerchantSettingDialog

@{
    Layout = "~/Views/Shared/_PersonalAreaDialog.cshtml";
}

<form id="frmMerchantSetting" autocomplete="off" style="max-height: 700px;overflow: auto;">
    @Html.HiddenFor(x => x.MerchantId)
    <div id="errorMessage"></div>
    <div class="form-group">
        @Html.RenderInputWithLabelOnTop("BaseAsset", "BaseAsset", Model.BaseAsset, focused: true)
    </div>
</form>

@Html.RenderSaveCancelButtonPair(Url.Action("AddOrEditMerchantSetting"), "#frmMerchantSetting")

src/Lykke.Service.PayBackoffice/Areas/LykkePay/Views/Merchants/AddOrEditMerchantTransferSettingDialog.cshtml
@using BackOffice.Models
@using BackOffice.Translates
@model BackOffice.Areas.LykkePay.Models.Merchants.AddOrEditMerchantTransferSettingsDialog

@{
    Layout = "~/Views/Shared/_PersonalAreaDialog.cshtml";
}
@{
    IEnumerable<ItemViewModel> ruleList = Model.RuleList.
        Select(m => new ItemViewModel {Id = m.Id, Title = m.DisplayName, Selected = (m.Id == Model.RuleId)}).ToArray();

    string currentRuleDisplayName = string.IsNullOrEmpty(Model.RuleId) 
        ? string.Empty 
        : Model.RuleList.SingleOrDefault(x => x.Id == Model.RuleId)?.DisplayName;
}

<form id="frmMerchantTransferSetting" autocomplete="off" style="max-height: 700px;overflow: auto;">
    @Html.HiddenFor(x => x.MerchantId)
    @Html.HiddenFor(x => x.IsNew)
    @Html.HiddenFor(x => x.Enabled)
    @if (!Model.IsNew)
    {
        @Html.HiddenFor(x => x.RuleId)
    }

    <div id="errorMessage"></div>

    <div class="form-group">
        @if (Model.IsNew)
        {
            @Html.RenderSelect2("Rule", "RuleId", ruleList, false, "Select rule ...")
        }
        else
        {
            @Html.RenderInputWithLabelOnTopReadOnly("Rule", currentRuleDisplayName)
        }
    </div>
    <div class="form-group">
        @Html.RenderTextAreaWithLabelOnTop("RuleInput", "Rule input", Model.RuleInput, "Please, add valid json...")
    </div>
</form>
@Html.RenderSaveCancelButtonPair(Url.Action("AddOrEditMerchantTransferSetting"), "#frmMerchantTransferSetting")
<script>
    $("[name='Enabled']").change(function(e) {
        $("#Enabled").val(e.currentTarget.checked);
    });
</script>

src/Lykke.Service.PayBackoffice/Areas/LykkePay/Views/Merchants/DeleteMerchantDialog.cshtml
@model BackOffice.Areas.LykkePay.Models.DeleteMerchantDialogViewModel

@{
    Layout = "~/Views/Shared/_PersonalAreaDialog.cshtml";
}

<form id="frmDeleteMerchant">

    <input style="display: none" name="Id" value="@Model.Id" />
    <h3>@Model.Name</h3>

</form>

@Html.RenderSaveCancelButtonPair(Url.Action("DeleteMerchant"), "#frmDeleteMerchant", "Confirm")

src/Lykke.Service.PayBackoffice/Areas/LykkePay/Views/Merchants/DeleteMerchantTransferSettingsDialog.cshtml
@model BackOffice.Areas.LykkePay.Models.Merchants.DeleteMerchantTransferSettingsDialogViewModel

@{
    Layout = "~/Views/Shared/_PersonalAreaDialog.cshtml";
}

<form id="frmDeleteMerchantTransferSettings">

    <input style="display: none" name="MerchantId" value="@Model.MerchantId" />
    <input style="display: none" name="RuleId" value="@Model.RuleId" />
    <h3>Rule name: @Model.RuleDisplayName</h3>

</form>

@Html.RenderSaveCancelButtonPair(Url.Action("DeleteMerchantTransferSettings"), "#frmDeleteMerchantTransferSettings", "Confirm")

src/Lykke.Service.PayBackoffice/Areas/LykkePay/Views/Merchants/DeleteMerchantVolatilitySettingsDialog.cshtml
@model BackOffice.Areas.LykkePay.Models.Merchants.DeleteMerchantVolatilitySettingsDialogViewModel

@{
    Layout = "~/Views/Shared/_PersonalAreaDialog.cshtml";
}

<form id="frmDeleteMerchantVolatilitySettings">

    <input style="display: none" name="MerchantId" value="@Model.MerchantId" />
    <h3>@Model.MerchantId</h3>

</form>

@Html.RenderSaveCancelButtonPair(Url.Action("DeleteMerchantVolatilitySettings"), "#frmDeleteMerchantVolatilitySettings", "Confirm")

src/Lykke.Service.PayBackoffice/Areas/LykkePay/Views/Merchants/Index.cshtml
@using BackOffice.Translates

<ul id="tabs" class="nav nav-tabs">
    <li id="merchants"><a data-toggle="tab" onclick="selectTab(this.parentNode.id, '@Url.Action("MerchantsPage")')">Merchants</a></li>
    <li id="merchantsSettings"><a data-toggle="tab" onclick="selectTab(this.parentNode.id, '@Url.Action("MerchantsSettingsPage")')">Settings</a></li>
    <li id="merchantVolatilitySettings"><a data-toggle="tab" onclick="selectTab(this.parentNode.id, '@Url.Action("MerchantVolatilitySettingsPage")')">Volatility settings</a></li>
    <li id="merchantTransferSettings"><a data-toogle="tab" onclick="selectTab(this.parentNode.id, '@Url.Action("MerchantTransferSettingsPage")')">BIL transfer settings</a></li>
</ul>

<div id="MerchantsPage" style="margin: 10px"></div>
<div id="MerchantsSettingsPage" style="margin: 10px"></div>
<div id="MerchantVolatilitySettingsPage" style="margin: 10px"></div>
<div id="MerchantTransferSettingsPage" style="margin: 10px"></div>

<script>
    function selectTab(tabId, url) {
        if ($('#' + tabId).hasClass('active'))
            return;
        $('#tabs').children('li').each(function() {
            (this.id === tabId) && $('#' + this.id).addClass('active') || $('#' + this.id).removeClass('active');
        });
        requests.doRequest({ url: url, divResult: '#MerchantsPage' });
    }
    selectTab('merchants', '@Url.Action("MerchantsPage")');
</script>

src/Lykke.Service.PayBackoffice/Areas/LykkePay/Views/Merchants/UploadLogoDialog.cshtml
@model BackOffice.Areas.LykkePay.Models.Merchants.UploadLogoDialogViewModel
@{
    Layout = "~/Views/Shared/_PersonalAreaDialog.cshtml";
}
@using (Html.BeginForm("UploadLogo", "Merchants", FormMethod.Post, new { enctype = "multipart/form-data", id = "UploadLogoForm" }))
{
    <div>
        @if (!string.IsNullOrEmpty(Model.LogoImage))
        {
            <div class="form-group">
                <label class="control-label">Logo</label>
                <br />
                <img width="150" src="data:image/jpeg;base64,@Model.LogoImage" />
            </div>
        }
        <div>
            <input type="file" name="file" style="visibility: hidden;" id="selectFileDialog" accept=".png,.jpg,.jpeg">
            <div class="form-inline">
                <input type="button" class="btn btn-info" onclick="$('#selectFileDialog').click();" value="Choose File" style="width: 30%" />
                <input type="text" id="subfile" class="form-control" required="required" style="width: 67%" autocomplete="off">
            </div>
            <br />
        </div>
    </div>

    <input name="MerchantId" type="hidden" value="@Model.MerchantId" />
    <input class="btn btn-primary" type="submit" name="Submit" id="Submit" value="Upload" />
}
<script>
    $(document).ready(function () {
        $('#UploadLogoForm').submit(function (event) {
            // disable form submit to avoid redirection, but use submit input to leave native HTML5 validation
            event.preventDefault();

            if (!$("#UploadLogoForm")[0].checkValidity()) {
                return;
            }

            uploadDocument();
        });
        $('#selectFileDialog').change(function () {
            $('#subfile').val(null);

            if ($(this)[0].files == null)
                return;

            var fileNames = [];
            var totalSize = 0;
            Array.prototype.every.call($(this)[0].files, file => {
                if (file.type == "image/png" || file.type == "image/jpeg") {
                    fileNames.push(file.name);
                    totalSize += file.size;
                }
                else
                {
                    alert("This file extension isn't supported. Allowed file extension is .png, .jpeg");
                    return;
                }
            });

            if (totalSize >= 10 * 1024 * 1024) {
                alert('File size cannot exceed 10 MB!');
                return;
            }

            $('#subfile').val(fileNames.join(', '));
        });

        // Make #subfile read-only, but allow HTML5 validations
        $("#subfile").keydown(function (e) {
            e.preventDefault();
            return;
        });
    });

    function ignoreKeyPress(e) {
        e.preventDefault();
    }

    function uploadDocument() {
        var myFormData = new FormData();

        var files = $('#selectFileDialog')[0].files;
        for (var i = 0; i < files.length ; i++) {
            myFormData.append(files[i].name, files[i]);
        }

        $('#UploadLogoForm').serializeArray().forEach(function (item, i, arr) {
            myFormData.append(item.name, item.value);
        });

        $.ajax({
            url: '@Url.Action("UploadLogo")',
            type: 'POST',
            headers: { 'RequestVerificationToken': getAntiForgeryCookie() },
            processData: false,
            contentType: false,
            dataType: 'json',
            data: myFormData,
            success: function (response) {

                var div = $(response.div);
                var divDataUrl = response.refreshUrl;
                var divError = $(response.divError);

                if (response.msg) {
                    divError.text(response.msg);
                } else {
                    ui.hideDialog();

                    if (div != null && divDataUrl != null) {

                        div.html('<div style="text-align:center; margin-top:20px;"><img src="/images/loading-pa.gif"/></div>');
                        div.show();

                        $.ajax({
                            url: divDataUrl,
                            type: 'POST',
                            headers: { 'RequestVerificationToken': getAntiForgeryCookie() },
                            success: function (response) {
                                div.html(response);
                                div.show();
                            }
                        });
                    }
                }
            },
            error: function () {
                ui.hideDialog();
            }
        });
    }
</script>